stages:
  - lint
  - security
  - quality
  - test

image: lappis/decidim-govbr:v1-release
services:
  - postgres:13.2-alpine
  - redis:latest

before_script:
  # Project setup
  - apt install -y build-essential curl git libssl-dev zlib1g-dev libicu-dev g++ gcc openssl libgit2-dev cmake pkg-config libpq-dev
  - bundle check || bundle install --jobs $(nproc)
  - npm install
  - yarn install

Lint:
  stage: lint
  script:
    - bundle exec rubocop

Security:
  stage: security
  script:
    - bundle exec brakeman --no-pager

Quality:
  stage: quality
  script:
    - gem install rubycritic
    - rubycritic -m -s 95 app/
  rules:
    - allow_failure: true

Testing:
  stage: test
  variables:
    POSTGRES_HOST: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: password
    RAILS_ENV: test
    REDIS_URL: redis://localhost:6379
    REDIS_CACHE_URL: redis://localhost:6380
  script:
    - apt-get update -yy && apt-get install build-essential libpq-dev -y
    - bundle install
    - bundle exec rails db:setup                
    - bundle exec rails test && bundle exec rspec
