# This file is meant to be a mirror of what we have in Decidim original's file
# which can be found in https://github.com/decidim/decidim/blob/release/0.27-stable/.rubocop_ruby.yml
#

# Call super to initialize state of the parent class.
Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 15
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  # If true, strings which span multiple lines using \ for continuation must
  # use the same type of quotes on each line.
  ConsistentQuotesInMultiline: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%":  ()
    "%i": ()
    "%q": ()
    "%Q": ()
    "%r": "{}"
    "%s": ()
    "%w": ()
    "%W": ()
    "%x": ()

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 180
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - "**/spec/**/*"
