inherit_from:
  - .rubocop_todo.yml
  - .rubocop_ruby.yml
  - .rubocop-disabled.yml

AllCops:
  Exclude:
    - "db/schema.rb"
    - "vendor/decidim-homes/**/*"
    - "db/seeds.rb"
    - "scripts/rails_admin.rb"
    - "setup/puma.production.rb"
    - "db/migrate/*"
    - "config/routes.rb"
